name: Release build for r8q

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-r8q:
    uses: ./.github/workflows/build.yml
    with:
      device: r8q
      device_name: Galaxy S20 FE
      build: build
